name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  package:
    runs-on: maxos
    needs: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - run: |
          make build
          make package
          echo "TAG=$(go run scripts/version/main.go)" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.TAG }}
