name: Tag
on:
  push:
    branches: [ "main" ]
    paths:
      - 'cmd/version.go'
jobs:
  test:
    uses: ./.github/workflows/test.yml
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: create tag
        env:
          GITHUB_PAT: ${{ secrets.PAT_ANAGUMA }}
        run: |
          TAG=$(go run scripts/version/main.go)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push https://x-access-token:${GITHUB_PAT}@github.com/${{ github.repository }} $TAG
